version: "3.9"
services:
  hasura:
    image: "hasura/graphql-engine:v2.16.1"
    ports:
      - '8080:8080'
    environment:
      HASURA_GRAPHQL_DATABASE_URL: 'postgres://postgres:mysecretpassword@database:5432/postgres'
      HASURA_GRAPHQL_ENABLE_CONSOLE: true
      HASURA_GRAPHQL_ENABLE_ALLOWLIST: true
  database:
    image: "postgres:15.1-alpine"
    ports:
      - '5432:5432'
    volumes:
      - '${PWD}/db/dump.sql:/docker-entrypoint-initdb.d/dump.sql'
    environment:
      FLASK_DEBUG: True
      POSTGRES_PASSWORD: mysecretpassword
  web:
    build: .
    ports:
      - '3000:3000'
    command: "npm start"
    volumes:
      - '${PWD}/src:/usr/local/app/src'
      - '${PWD}/public:/usr/local/app/public'
      - '${PWD}/codegen.ts:/usr/local/app/codegen.ts'
      - '${PWD}/tsconfig.json:/usr/local/app/tsconfig.json'
